sudo: required
services:
  - docker

before_install:
  - docker build -t olgamikholenko/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true olgamikholenko/docker-react npm run test -- --coverage